config/routes.rb
Stairchallenge::Application.routes.draw do
  devise_for :users

  match 'map' => 'stairways#index'
  resources :stairways 
  resources :user_runs

  root :to => 'home#index'

end

app/models/stairway.rb
class Stairway < ActiveRecord::Base
   has_many :user_runs
   acts_as_gmappable :latitude => "latitude", :longitude => "longitude", :description => "description" 

   def times_ran_by_user user
     if user
       self.user_runs.where(user_id: user.id).count
     end
   end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :confirmable,
  # :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  # attr_accessible :title, :body

  has_many :user_runs
end

app/models/user_run.rb
class UserRun < ActiveRecord::Base
  attr_accessible :timestamp, :stairway_id, :user_id
  belongs_to :user
  belongs_to :stairway
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  protect_from_forgery
  
  def index
  end
end

app/controllers/stairways_controller.rb
class StairwaysController < ApplicationController
  protect_from_forgery
  helper_method :sort_column, :sort_direction
  
  def index
    @stairways = Stairway.order(sort_column + ' ' + sort_direction)
    @user = current_user
    @json = Stairway.all.to_gmaps4rails do |stairway, marker|
      marker.infowindow render_to_string(:partial => "/stairways/infowindow", :locals => { :stairway => stairway, :user => current_user})
    end
  end

  private
  def sort_column
    Stairway.column_names.include?(params[:sort]) ? params[:sort] : 'name'
  end

  def sort_direction
    ['asc', 'desc'].include?(params[:direction]) ? params[:direction] : 'asc'
  end
end

app/controllers/user_runs_controller.rb
class UserRunsController < ApplicationController
  protect_from_forgery

  def create
    @user_run = UserRun.new(params[:user_run])
    @user_run.save
    redirect_to stairways_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def sortable(column, title = nil)
    title ||= column.titleize
    css_class = column == sort_column ? "current #{sort_direction}" : nil
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to title, {:sort => column, :direction => direction}, {:class => css_class}
  end
end

app/views/home/index.html.erb
Welcome to the Stairway Challenge!
<% if current_user %>
  <%= current_user.email %>
<% end %> 

app/views/layouts/_navigation.html.erb
<%= link_to "Stairway Challenge Home", root_path, :class => 'brand' %>
<ul class="nav">
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Logout', destroy_user_session_path, :method=>'delete' %>
    </li>
  <% else %>
    <li>
    <%= link_to 'Login', new_user_session_path %>
    </li>
  <% end %>
  <% if user_signed_in? %>
    <li>
    <%= link_to 'Edit account', edit_user_registration_path %>
    </li>
 <% else %>
    <li>
    <%= link_to 'Sign up', new_user_registration_path %>
    </li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Stairchallenge</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header class="navbar navbar-fixed-top">
    <nav class="navbar-inner">
      <div class="container">
        <%= render 'layouts/navigation' %>
      </div>
    </nav>
  </header>

<%= yield %>

</body>
</html>

app/views/stairways/_infowindow.html.erb
<% if user %>
  <%= form_for stairway.user_runs.new, :url => user_runs_path do |f| %>
    <%= f.hidden_field :stairway_id, value: stairway.id %>
    <%= f.hidden_field :user_id, value: user.id %>
    <%= f.submit "Add run" %>
  <% end %>
<% end %>
<%= stairway.description.html_safe %>

app/views/stairways/index.html.erb
  <title>Stairways</title>
  <%#= stylesheet_link_tag    "application", :media => "all" %>
  <%= stylesheet_link_tag    'gmaps4rails' %>
  <%#= javascript_include_tag "application" %>
  <%#= csrf_meta_tags %>
  <%#= yield :head %>
</head>
<body>

<%= gmaps("markers" => {"data" => @json, "options" => {"rich_marker" => true } }) %>
<%= yield :scripts %>

<table class="table">
  <thead>
    <tr>
      <th><%= sortable "name" %></th>
      <th><%= sortable "stairs" %></th>
      <th><%= "Times Ran By You" %></th>
      <th><%= "Times Ran By Everyone" %></th>
    </tr>
  </thead>
  <tbody>
    <%@stairways.each do |stairway|%>
      <tr>
        <td><%= stairway.name %></td>
        <td><%= stairway.stairs %></td>
        <td><%= stairway.times_ran_by_user(@user) %></td>
        <td><%= stairway.user_runs.count %></td>
      </tr>
  </tbody>
  <%end%>
</table>